import Fruits from "./assets/fruit.jpg";
import Vegetables from "./assets/vegitables.png";

//CardCarosuel Component Data here.......!!
export const user = [
  {
    id: 1,
    email: "sailesh@gmail.com",
    pass: "112233",
    cart: [
      {
        productId: 2,
        quantity: 2,
      },
    ],
  },
  {
    id: 1,
    email: "sailesh@gmail.com",
    pass: "112233",
  },
];
export const cardsCarouselData = [
  {
    id: 1,
    title: "Fruits",
    image: Fruits,
  },
  {
    id: 2,
    title: "toys",
    image: Fruits,
  },
  {
    id: 3,
    title: "Snacks",
    image: Fruits,
  },
  {
    id: 4,
    title: "Oil",
    image: Fruits,
  },
  {
    id: 5,
    title: "Vegetables",
    image: Fruits,
  },
  {
    id: 6,
    title: "Dairy",
    image: Fruits,
  },
];
// slidebar data
export const categories = [
  "All Products",
  "Vegetables",
  "Fruits",
  "Toys",
  "Dairy",
  "Snacks",
  "Grains",
  "Oils",
  "Sweets",
  "Cereals",
  "Legumes",
  "Beverages",
  "Frozen Foods",
  "Condiments",
  "Bakery",
  "Meat & Seafood",
  "Spices",
];
// CardData here ...!!
export const AllcardsData = [
  {
    id: 1,
    title: "Bananas",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹50" },
      { quantity: "1kg", price: "₹90" },
    ],
    unit: "g",
    para: "Fresh bananas",
    category: "Fruits",
  },
  {
    id: 2,
    title: "Oranges",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹60" },
      { quantity: "1kg", price: "₹110" },
    ],
    unit: "g",
    para: "Juicy and sweet oranges.",
    category: "Fruits",
  },
  {
    id: 3,
    title: "Apples",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹80" },
      { quantity: "1kg", price: "₹150" },
    ],
    unit: "g",
    para: "Crisp and refreshing apples.",
    category: "Fruits",
  },
  {
    id: 4,
    title: "Grapes",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹100" },
      { quantity: "1kg", price: "₹180" },
    ],
    unit: "g",
    para: "Sweet and juicy grapes.",
    category: "Fruits",
  },
  {
    id: 5,
    title: "Mangoes",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹120" },
      { quantity: "1kg", price: "₹220" },
    ],
    unit: "g",
    para: "Ripe and delicious mangoes.",
    category: "Fruits",
  },
  {
    id: 6,
    title: "Strawberries",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹150" },
      { quantity: "500g", price: "₹280" },
    ],
    unit: "g",
    para: "Fresh and sweet strawberries.",
    category: "Fruits",
  },
  {
    id: 7,
    title: "Watermelons",
    img: Vegetables,
    options: [
      { quantity: "1kg", price: "₹70" },
      { quantity: "2kg", price: "₹130" },
    ],
    unit: "kg",
    para: "Hydrating and refreshing watermelon.",
    category: "Fruits",
  },
  {
    id: 8,
    title: "Pineapples",
    img: Vegetables,
    options: [
      { quantity: "1 piece", price: "₹90" },
      { quantity: "2 pieces", price: "₹170" },
    ],
    unit: "pieces",
    para: "Tropical and sweet pineapples.",
    category: "Fruits",
  },
  {
    id: 9,
    title: "Peaches",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹120" },
      { quantity: "1kg", price: "₹230" },
    ],
    unit: "g",
    para: "Sweet and juicy peaches.",
    category: "Fruits",
  },
  {
    id: 10,
    title: "Cherries",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹200" },
      { quantity: "500g", price: "₹380" },
    ],
    unit: "g",
    para: "Delicious and tart cherries.",
    category: "Fruits",
  },
  {
    id: 11,
    title: "Kiwis",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹90" },
      { quantity: "500g", price: "₹170" },
    ],
    unit: "g",
    para: "Tangy and sweet kiwis.",
    category: "Fruits",
  },
  {
    id: 12,
    title: "Papayas",
    img: Vegetables,
    options: [
      { quantity: "1 piece", price: "₹80" },
      { quantity: "2 pieces", price: "₹150" },
    ],
    unit: "pieces",
    para: "Sweet and tropical papayas.",
    category: "Fruits",
  },
  {
    id: 13,
    title: "Pears",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹90" },
      { quantity: "1kg", price: "₹170" },
    ],
    unit: "g",
    para: "Juicy and soft pears.",
    category: "Fruits",
  },
  {
    id: 14,
    title: "Lemons",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹60" },
      { quantity: "500g", price: "₹110" },
    ],
    unit: "g",
    para: "Tangy and refreshing lemons.",
    category: "Fruits",
  },
  {
    id: 15,
    title: "Blackberries",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹120" },
      { quantity: "500g", price: "₹220" },
    ],
    unit: "g",
    para: "Delicious and sweet blackberries.",
    category: "Fruits",
  },
  {
    id: 16,
    title: "Raspberries",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹140" },
      { quantity: "500g", price: "₹260" },
    ],
    unit: "g",
    para: "Tart and sweet raspberries.",
    category: "Fruits",
  },
  {
    id: 17,
    title: "Coconuts",
    img: Vegetables,
    options: [
      { quantity: "1 piece", price: "₹150" },
      { quantity: "2 pieces", price: "₹290" },
    ],
    unit: "pieces",
    para: "Fresh and tropical coconuts.",
    category: "Fruits",
  },
  {
    id: 18,
    title: "Avocados",
    img: Vegetables,
    options: [
      { quantity: "1 piece", price: "₹80" },
      { quantity: "2 pieces", price: "₹150" },
    ],
    unit: "pieces",
    para: "Creamy and nutritious avocados.",
    category: "Fruits",
  },
  {
    id: 19,
    title: "Dragon Fruit",
    img: Vegetables,
    options: [
      { quantity: "1 piece", price: "₹200" },
      { quantity: "2 pieces", price: "₹390" },
    ],
    unit: "pieces",
    para: "Exotic and refreshing dragon fruit.",
    category: "Fruits",
  },
  {
    id: 20,
    title: "Lychees",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹160" },
      { quantity: "500g", price: "₹300" },
    ],
    unit: "g",
    para: "Sweet and aromatic lychees.",
    category: "Fruits",
  },
  {
    id: 21,
    title: "Tomato",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹30" },
      { quantity: "1kg", price: "₹55" },
    ],
    unit: "g",
    para: "Fresh and juicy tomatoes.",
    category: "Vegetables",
  },
  {
    id: 22,
    title: "Carrot",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹40" },
      { quantity: "1kg", price: "₹75" },
    ],
    unit: "g",
    para: "Crunchy and sweet carrots.",
    category: "Vegetables",
  },
  {
    id: 23,
    title: "Potato",
    img: Vegetables,
    options: [
      { quantity: "1kg", price: "₹60" },
      { quantity: "2kg", price: "₹110" },
    ],
    unit: "kg",
    para: "Versatile and delicious potatoes.",
    category: "Vegetables",
  },
  {
    id: 24,
    title: "Cabbage",
    img: Vegetables,
    options: [
      { quantity: "1kg", price: "₹40" },
      { quantity: "2kg", price: "₹75" },
    ],
    unit: "kg",
    para: "Fresh and crunchy cabbage.",
    category: "Vegetables",
  },
  {
    id: 25,
    title: "Onion",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹25" },
      { quantity: "1kg", price: "₹45" },
    ],
    unit: "g",
    para: "Strong-flavored onions.",
    category: "Vegetables",
  },
  {
    id: 26,
    title: "Spinach",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹20" },
      { quantity: "500g", price: "₹35" },
    ],
    unit: "g",
    para: "Fresh and healthy spinach.",
    category: "Vegetables",
  },
  {
    id: 27,
    title: "Broccoli",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹70" },
      { quantity: "1kg", price: "₹130" },
    ],
    unit: "g",
    para: "Nutritious and tasty broccoli.",
    category: "Vegetables",
  },
  {
    id: 28,
    title: "Cauliflower",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹50" },
      { quantity: "1kg", price: "₹90" },
    ],
    unit: "g",
    para: "Delicious and versatile cauliflower.",
    category: "Vegetables",
  },
  {
    id: 29,
    title: "Bell Pepper",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹60" },
      { quantity: "1kg", price: "₹110" },
    ],
    unit: "g",
    para: "Colorful and crunchy bell peppers.",
    category: "Vegetables",
  },
  {
    id: 30,
    title: "Zucchini",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹50" },
      { quantity: "1kg", price: "₹90" },
    ],
    unit: "g",
    para: "Fresh and healthy zucchini.",
    category: "Vegetables",
  },
  {
    id: 31,
    title: "Eggplant",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹40" },
      { quantity: "1kg", price: "₹70" },
    ],
    unit: "g",
    para: "Versatile and delicious eggplant.",
    category: "Vegetables",
  },
  {
    id: 32,
    title: "Pumpkin",
    img: Vegetables,
    options: [
      { quantity: "1kg", price: "₹80" },
      { quantity: "2kg", price: "₹150" },
    ],
    unit: "kg",
    para: "Sweet and nutritious pumpkin.",
    category: "Vegetables",
  },
  {
    id: 33,
    title: "Beetroot",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹30" },
      { quantity: "1kg", price: "₹55" },
    ],
    unit: "g",
    para: "Healthy and sweet beetroot.",
    category: "Vegetables",
  },
  {
    id: 34,
    title: "Radish",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹25" },
      { quantity: "1kg", price: "₹45" },
    ],
    unit: "g",
    para: "Crisp and spicy radish.",
    category: "Vegetables",
  },
  {
    id: 35,
    title: "Lettuce",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹20" },
      { quantity: "500g", price: "₹35" },
    ],
    unit: "g",
    para: "Fresh and crunchy lettuce.",
    category: "Vegetables",
  },
  {
    id: 36,
    title: "Action Figure",
    img: Vegetables,
    options: [
      { quantity: "1", price: "₹300" },
      { quantity: "2", price: "₹550" },
    ],
    unit: "pieces",
    para: "Exciting action figures for imaginative play.",
    category: "Toys",
  },
  {
    id: 37,
    title: "Building Blocks",
    img: Vegetables,
    options: [
      { quantity: "1 set", price: "₹700" },
      { quantity: "2 sets", price: "₹1300" },
    ],
    unit: "pieces",
    para: "Endless fun with building blocks.",
    category: "Toys",
  },
  {
    id: 38,
    title: "Stuffed Animal",
    img: Vegetables,
    options: [
      { quantity: "1", price: "₹400" },
      { quantity: "2", price: "₹750" },
    ],
    unit: "pieces",
    para: "Soft and cuddly stuffed animals.",
    category: "Toys",
  },
  {
    id: 39,
    title: "Puzzle",
    img: Vegetables,
    options: [
      { quantity: "1", price: "₹250" },
      { quantity: "2", price: "₹450" },
    ],
    unit: "pieces",
    para: "Challenging puzzles for brainy fun.",
    category: "Toys",
  },
  {
    id: 40,
    title: "Remote Control Car",
    img: Vegetables,
    options: [
      { quantity: "1", price: "₹900" },
      { quantity: "2", price: "₹1700" },
    ],
    unit: "pieces",
    para: "Fast and fun remote control cars.",
    category: "Toys",
  },
  {
    id: 41,
    title: "Dollhouse",
    img: Vegetables,
    options: [
      { quantity: "1", price: "₹1500" },
      { quantity: "2", price: "₹2800" },
    ],
    unit: "pieces",
    para: "Create your dream home with a dollhouse.",
    category: "Toys",
  },
  {
    id: 42,
    title: "Board Game",
    img: Vegetables,
    options: [
      { quantity: "1", price: "₹600" },
      { quantity: "2", price: "₹1100" },
    ],
    unit: "pieces",
    para: "Fun for the whole family with board games.",
    category: "Toys",
  },
  {
    id: 43,
    title: "Toy Train Set",
    img: Vegetables,
    options: [
      { quantity: "1 set", price: "₹1200" },
      { quantity: "2 sets", price: "₹2200" },
    ],
    unit: "pieces",
    para: "Enjoy hours of fun with a toy train set.",
    category: "Toys",
  },
  {
    id: 44,
    title: "Play-Doh Set",
    img: Vegetables,
    options: [
      { quantity: "1 set", price: "₹500" },
      { quantity: "2 sets", price: "₹950" },
    ],
    unit: "pieces",
    para: "Creative fun with Play-Doh.",
    category: "Toys",
  },
  {
    id: 45,
    title: "Marble Run",
    img: Vegetables,
    options: [
      { quantity: "1 set", price: "₹800" },
      { quantity: "2 sets", price: "₹1500" },
    ],
    unit: "pieces",
    para: "Build your own marble run!",
    category: "Toys",
  },
  {
    id: 46,
    title: "Balloon Launcher",
    img: Vegetables,
    options: [
      { quantity: "1", price: "₹400" },
      { quantity: "2", price: "₹700" },
    ],
    unit: "pieces",
    para: "Launch balloons for fun and excitement.",
    category: "Toys",
  },
  {
    id: 47,
    title: "Kite",
    img: Vegetables,
    options: [
      { quantity: "1", price: "₹200" },
      { quantity: "2", price: "₹350" },
    ],
    unit: "pieces",
    para: "Fly a colorful kite in the sky.",
    category: "Toys",
  },
  {
    id: 48,
    title: "Toy Robot",
    img: Vegetables,
    options: [
      { quantity: "1", price: "₹500" },
      { quantity: "2", price: "₹950" },
    ],
    unit: "pieces",
    para: "Interactive and fun toy robot.",
    category: "Toys",
  },
  {
    id: 49,
    title: "Magic Set",
    img: Vegetables,
    options: [
      { quantity: "1", price: "₹600" },
      { quantity: "2", price: "₹1100" },
    ],
    unit: "pieces",
    para: "Perform amazing tricks with a magic set.",
    category: "Toys",
  },
  {
    id: 50,
    title: "Nerf Blaster",
    img: Vegetables,
    options: [
      { quantity: "1", price: "₹800" },
      { quantity: "2", price: "₹1500" },
    ],
    unit: "pieces",
    para: "Exciting Nerf blasters for action-packed play.",
    category: "Toys",
  },
  {
    id: 51,
    title: "Milk",
    img: Vegetables,
    options: [
      { quantity: "1L", price: "₹50" },
      { quantity: "2L", price: "₹90" },
    ],
    unit: "liters",
    para: "Fresh and nutritious milk.",
    category: "Dairy",
  },
  {
    id: 52,
    title: "Butter",
    img: Vegetables,
    options: [
      { quantity: "200g", price: "₹80" },
      { quantity: "500g", price: "₹180" },
    ],
    unit: "grams",
    para: "Creamy and rich butter for cooking.",
    category: "Dairy",
  },
  {
    id: 53,
    title: "Cheese",
    img: Vegetables,
    options: [
      { quantity: "200g", price: "150" },
      { quantity: "500g", price: "350" },
    ],
    unit: "grams",
    para: "Delicious cheese for all your dishes.",
    category: "Dairy",
  },
  {
    id: 54,
    title: "Yogurt",
    img: Vegetables,
    options: [
      { quantity: "200g", price: "₹40" },
      { quantity: "500g", price: "₹90" },
    ],
    unit: "grams",
    para: "Creamy yogurt, perfect for snacks.",
    category: "Dairy",
  },
  {
    id: 55,
    title: "Cream",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹100" },
      { quantity: "500g", price: "₹180" },
    ],
    unit: "grams",
    para: "Rich cream for cooking and desserts.",
    category: "Dairy",
  },
  {
    id: 56,
    title: "Paneer",
    img: Vegetables,
    options: [
      { quantity: "200g", price: "₹70" },
      { quantity: "500g", price: "₹160" },
    ],
    unit: "grams",
    para: "Fresh paneer for your favorite dishes.",
    category: "Dairy",
  },
  {
    id: 57,
    title: "Ice Cream",
    img: Vegetables,
    options: [
      { quantity: "500ml", price: "₹150" },
      { quantity: "1L", price: "₹280" },
    ],
    unit: "liters",
    para: "Delicious ice cream for a sweet treat.",
    category: "Dairy",
  },
  {
    id: 58,
    title: "Condensed Milk",
    img: Vegetables,
    options: [
      { quantity: "200g", price: "₹60" },
      { quantity: "400g", price: "₹110" },
    ],
    unit: "grams",
    para: "Sweetened condensed milk for desserts.",
    category: "Dairy",
  },
  {
    id: 59,
    title: "Ghee",
    img: Vegetables,
    options: [
      { quantity: "200g", price: "₹200" },
      { quantity: "500g", price: "₹400" },
    ],
    unit: "grams",
    para: "Pure ghee for cooking and flavor.",
    category: "Dairy",
  },
  {
    id: 60,
    title: "Whey Protein",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹1200" },
      { quantity: "1kg", price: "₹2200" },
    ],
    unit: "grams",
    para: "High-quality whey protein for fitness.",
    category: "Dairy",
  },
  {
    id: 61,
    title: "Ricotta Cheese",
    img: Vegetables,
    options: [
      { quantity: "200g", price: "₹150" },
      { quantity: "500g", price: "₹280" },
    ],
    unit: "grams",
    para: "Fresh ricotta cheese for cooking.",
    category: "Dairy",
  },
  {
    id: 62,
    title: "Sour Cream",
    img: Vegetables,
    options: [
      { quantity: "200g", price: "₹90" },
      { quantity: "500g", price: "₹160" },
    ],
    unit: "grams",
    para: "Creamy sour cream for dips and dishes.",
    category: "Dairy",
  },
  {
    id: 63,
    title: "Cottage Cheese",
    img: Vegetables,
    options: [
      { quantity: "200g", price: "₹70" },
      { quantity: "500g", price: "₹140" },
    ],
    unit: "grams",
    para: "Fresh cottage cheese for salads.",
    category: "Dairy",
  },
  {
    id: 64,
    title: "Milk Powder",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹250" },
      { quantity: "1kg", price: "₹450" },
    ],
    unit: "grams",
    para: "Convenient milk powder for cooking.",
    category: "Dairy",
  },
  {
    id: 65,
    title: "Almond Milk",
    img: Vegetables,
    options: [
      { quantity: "1L", price: "₹150" },
      { quantity: "2L", price: "₹280" },
    ],
    unit: "liters",
    para: "Nutty almond milk, dairy-free option.",
    category: "Dairy",
  },
  {
    id: 66,
    title: "Potato Chips",
    img: Vegetables,
    options: [
      { quantity: "100g", price: "₹30" },
      { quantity: "200g", price: "₹50" },
    ],
    unit: "grams",
    para: "Crispy potato chips for snacking.",
    category: "Snacks",
  },
  {
    id: 67,
    title: "Chocolate Bar",
    img: Vegetables,
    options: [
      { quantity: "50g", price: "₹40" },
      { quantity: "100g", price: "₹70" },
    ],
    unit: "grams",
    para: "Rich chocolate bars for a sweet treat.",
    category: "Snacks",
  },
  {
    id: 68,
    title: "Nuts Mix",
    img: Vegetables,
    options: [
      { quantity: "100g", price: "₹150" },
      { quantity: "250g", price: "₹350" },
    ],
    unit: "grams",
    para: "A healthy mix of nuts for snacking.",
    category: "Snacks",
  },
  {
    id: 69,
    title: "Granola Bars",
    img: Vegetables,
    options: [
      { quantity: "50g", price: "₹30" },
      { quantity: "100g", price: "₹50" },
    ],
    unit: "grams",
    para: "Nutritious granola bars for energy.",
    category: "Snacks",
  },
  {
    id: 70,
    title: "Popcorn",
    img: Vegetables,
    options: [
      { quantity: "100g", price: "₹40" },
      { quantity: "200g", price: "₹70" },
    ],
    unit: "grams",
    para: "Light and fluffy popcorn for movie nights.",
    category: "Snacks",
  },
  {
    id: 71,
    title: "Cookies",
    img: Vegetables,
    options: [
      { quantity: "100g", price: "₹60" },
      { quantity: "200g", price: "₹100" },
    ],
    unit: "grams",
    para: "Delicious cookies for a sweet snack.",
    category: "Snacks",
  },
  {
    id: 72,
    title: "Pretzels",
    img: Vegetables,
    options: [
      { quantity: "100g", price: "₹40" },
      { quantity: "250g", price: "₹80" },
    ],
    unit: "grams",
    para: "Crunchy pretzels for munching.",
    category: "Snacks",
  },
  {
    id: 73,
    title: "Fruit Snacks",
    img: Vegetables,
    options: [
      { quantity: "100g", price: "₹60" },
      { quantity: "200g", price: "₹110" },
    ],
    unit: "grams",
    para: "Chewy fruit snacks for kids.",
    category: "Snacks",
  },
  {
    id: 74,
    title: "Rice Crackers",
    img: Vegetables,
    options: [
      { quantity: "100g", price: "₹50" },
      { quantity: "250g", price: "₹90" },
    ],
    unit: "grams",
    para: "Light and crispy rice crackers.",
    category: "Snacks",
  },
  {
    id: 75,
    title: "Trail Mix",
    img: Vegetables,
    options: [
      { quantity: "100g", price: "₹150" },
      { quantity: "250g", price: "₹300" },
    ],
    unit: "grams",
    para: "A nutritious mix for energy on the go.",
    category: "Snacks",
  },
  {
    id: 76,
    title: "Cheese Puffs",
    img: Vegetables,
    options: [
      { quantity: "100g", price: "₹40" },
      { quantity: "200g", price: "₹70" },
    ],
    unit: "grams",
    para: "Crispy cheese puffs for a cheesy snack.",
    category: "Snacks",
  },
  {
    id: 77,
    title: "Savory Biscuits",
    img: Vegetables,
    options: [
      { quantity: "100g", price: "₹50" },
      { quantity: "200g", price: "₹90" },
    ],
    unit: "grams",
    para: "Savory biscuits for snacking anytime.",
    category: "Snacks",
  },
  {
    id: 78,
    title: "Energy Bars",
    img: Vegetables,
    options: [
      { quantity: "50g", price: "₹40" },
      { quantity: "100g", price: "₹70" },
    ],
    unit: "grams",
    para: "Energy bars for a quick boost.",
    category: "Snacks",
  },
  {
    id: 79,
    title: "Cheese Crackers",
    img: Vegetables,
    options: [
      { quantity: "100g", price: "₹60" },
      { quantity: "200g", price: "₹110" },
    ],
    unit: "grams",
    para: "Crispy crackers with cheese flavor.",
    category: "Snacks",
  },
  {
    id: 80,
    title: "Chickpea Snacks",
    img: Vegetables,
    options: [
      { quantity: "100g", price: "₹80" },
      { quantity: "200g", price: "₹150" },
    ],
    unit: "grams",
    para: "Healthy chickpea snacks for a crunchy treat.",
    category: "Snacks",
  },
  {
    id: 81,
    title: "Rice",
    img: Vegetables,
    options: [
      { quantity: "1kg", price: "₹80" },
      { quantity: "5kg", price: "₹400" },
    ],
    unit: "kg",
    para: "Premium quality rice for daily meals.",
    category: "Grains",
  },
  {
    id: 82,
    title: "Wheat Flour",
    img: Vegetables,
    options: [
      { quantity: "1kg", price: "₹60" },
      { quantity: "5kg", price: "₹280" },
    ],
    unit: "kg",
    para: "Finely milled wheat flour for baking.",
    category: "Grains",
  },
  {
    id: 83,
    title: "Oats",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹50" },
      { quantity: "1kg", price: "₹90" },
    ],
    unit: "grams",
    para: "Healthy oats for a nutritious breakfast.",
    category: "Grains",
  },
  {
    id: 84,
    title: "Quinoa",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹150" },
      { quantity: "1kg", price: "280" },
    ],
    unit: "grams",
    para: "Nutritious quinoa for salads and sides.",
    category: "Grains",
  },
  {
    id: 85,
    title: "Barley",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹70" },
      { quantity: "1kg", price: "₹120" },
    ],
    unit: "grams",
    para: "Nutritious barley for soups and stews.",
    category: "Grains",
  },
  {
    id: 86,
    title: "Millet",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹80" },
      { quantity: "1kg", price: "₹150" },
    ],
    unit: "grams",
    para: "Healthy millet for gluten-free meals.",
    category: "Grains",
  },
  {
    id: 87,
    title: "Cornmeal",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹60" },
      { quantity: "1kg", price: "₹100" },
    ],
    unit: "grams",
    para: "Ground cornmeal for baking and cooking.",
    category: "Grains",
  },
  {
    id: 88,
    title: "Rye Flour",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹70" },
      { quantity: "1kg", price: "₹120" },
    ],
    unit: "grams",
    para: "Rye flour for hearty breads.",
    category: "Grains",
  },
  {
    id: 89,
    title: "Sorghum",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹80" },
      { quantity: "1kg", price: "₹140" },
    ],
    unit: "grams",
    para: "Sorghum grain for gluten-free recipes.",
    category: "Grains",
  },
  {
    id: 90,
    title: "Brown Rice",
    img: Vegetables,
    options: [
      { quantity: "1kg", price: "90" },
      { quantity: "5kg", price: "450" },
    ],
    unit: "kg",
    para: "Nutritious brown rice for healthy meals.",
    category: "Grains",
  },
  {
    id: 91,
    title: "Spelt",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹100" },
      { quantity: "1kg", price: "₹180" },
    ],
    unit: "grams",
    para: "Ancient grain spelt for healthy baking.",
    category: "Grains",
  },
  {
    id: 92,
    title: "Teff",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹120" },
      { quantity: "1kg", price: "₹220" },
    ],
    unit: "grams",
    para: "Tiny grains of teff for nutritious recipes.",
    category: "Grains",
  },
  {
    id: 93,
    title: "Buckwheat",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹90" },
      { quantity: "1kg", price: "₹160" },
    ],
    unit: "grams",
    para: "Gluten-free buckwheat for versatile cooking.",
    category: "Grains",
  },
  {
    id: 94,
    title: "Farro",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹100" },
      { quantity: "1kg", price: "₹180" },
    ],
    unit: "grams",
    para: "Nutty farro for salads and sides.",
    category: "Grains",
  },
  {
    id: 95,
    title: "Chia Seeds",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹150" },
      { quantity: "500g", price: "₹280" },
    ],
    unit: "grams",
    para: "Nutritious chia seeds for smoothies.",
    category: "Grains",
  },
  {
    id: 96,
    title: "Flax Seeds",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹100" },
      { quantity: "500g", price: "₹180" },
    ],
    unit: "grams",
    para: "Healthy flax seeds for baking and smoothies.",
    category: "Grains",
  },
  {
    id: 97,
    title: "Pasta",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹70" },
      { quantity: "1kg", price: "₹130" },
    ],
    unit: "grams",
    para: "Delicious pasta for quick meals.",
    category: "Grains",
  },
  {
    id: 98,
    title: "Bulgur Wheat",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹60" },
      { quantity: "1kg", price: "₹110" },
    ],
    unit: "grams",
    para: "Quick-cooking bulgur wheat for salads.",
    category: "Grains",
  },
  {
    id: 99,
    title: "Couscous",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹60" },
      { quantity: "1kg", price: "₹110" },
    ],
    unit: "grams",
    para: "Fluffy couscous for a quick side dish.",
    category: "Grains",
  },
  {
    id: 100,
    title: "Semolina",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹50" },
      { quantity: "1kg", price: "₹90" },
    ],
    unit: "grams",
    para: "Versatile semolina for various recipes.",
    category: "Grains",
  },
  {
    id: 101,
    title: "Olive Oil",
    img: Vegetables,
    options: [
      { quantity: "250ml", price: "₹300" },
      { quantity: "500ml", price: "₹500" },
    ],
    unit: "ml",
    para: "Extra virgin olive oil for cooking and dressing.",
    category: "Oils",
  },
  {
    id: 102,
    title: "Coconut Oil",
    img: Vegetables,
    options: [
      { quantity: "250ml", price: "₹150" },
      { quantity: "500ml", price: "₹280" },
    ],
    unit: "ml",
    para: "Pure coconut oil for cooking and skin care.",
    category: "Oils",
  },
  {
    id: 103,
    title: "Sunflower Oil",
    img: Vegetables,
    options: [
      { quantity: "1L", price: "₹180" },
      { quantity: "5L", price: "₹800" },
    ],
    unit: "L",
    para: "Light and healthy sunflower oil for frying.",
    category: "Oils",
  },
  {
    id: 104,
    title: "Vegetable Oil",
    img: Vegetables,
    options: [
      { quantity: "1L", price: "₹150" },
      { quantity: "5L", price: "₹700" },
    ],
    unit: "L",
    para: "Multi-purpose vegetable oil for all cooking.",
    category: "Oils",
  },
  {
    id: 105,
    title: "Sesame Oil",
    img: Vegetables,
    options: [
      { quantity: "250ml", price: "₹250" },
      { quantity: "500ml", price: "₹450" },
    ],
    unit: "ml",
    para: "Flavorful sesame oil for Asian cooking.",
    category: "Oils",
  },
  {
    id: 106,
    title: "Mustard Oil",
    img: Vegetables,
    options: [
      { quantity: "1L", price: "₹160" },
      { quantity: "5L", price: "₹750" },
    ],
    unit: "L",
    para: "Strong and pungent mustard oil for pickling.",
    category: "Oils",
  },
  {
    id: 107,
    title: "Groundnut Oil",
    img: Vegetables,
    options: [
      { quantity: "1L", price: "₹190" },
      { quantity: "5L", price: "₹850" },
    ],
    unit: "L",
    para: "Nutty groundnut oil for frying and cooking.",
    category: "Oils",
  },
  {
    id: 108,
    title: "Grapeseed Oil",
    img: Vegetables,
    options: [
      { quantity: "250ml", price: "₹350" },
      { quantity: "500ml", price: "₹600" },
    ],
    unit: "ml",
    para: "Light grapeseed oil for healthy frying.",
    category: "Oils",
  },
  {
    id: 109,
    title: "Avocado Oil",
    img: Vegetables,
    options: [
      { quantity: "250ml", price: "₹500" },
      { quantity: "500ml", price: "₹900" },
    ],
    unit: "ml",
    para: "Rich avocado oil for cooking and dressings.",
    category: "Oils",
  },
  {
    id: 110,
    title: "Walnut Oil",
    img: Vegetables,
    options: [
      { quantity: "250ml", price: "₹450" },
      { quantity: "500ml", price: "₹800" },
    ],
    unit: "ml",
    para: "Nutty walnut oil for flavoring dishes.",
    category: "Oils",
  },
  {
    id: 111,
    title: "Pumpkin Seed Oil",
    img: Vegetables,
    options: [
      { quantity: "250ml", price: "₹400" },
      { quantity: "500ml", price: "₹700" },
    ],
    unit: "ml",
    para: "Nutty pumpkin seed oil for dressings.",
    category: "Oils",
  },
  {
    id: 112,
    title: "Coconut Milk",
    img: Vegetables,
    options: [
      { quantity: "400ml", price: "₹100" },
      { quantity: "1L", price: "₹250" },
    ],
    unit: "ml",
    para: "Creamy coconut milk for cooking and desserts.",
    category: "Oils",
  },
  {
    id: 113,
    title: "Tung Oil",
    img: Vegetables,
    options: [
      { quantity: "500ml", price: "₹500" },
      { quantity: "1L", price: "₹950" },
    ],
    unit: "ml",
    para: "Natural tung oil for finishing wood products.",
    category: "Oils",
  },
  {
    id: 114,
    title: "Flaxseed Oil",
    img: Vegetables,
    options: [
      { quantity: "250ml", price: "₹300" },
      { quantity: "500ml", price: "₹500" },
    ],
    unit: "ml",
    para: "Nutritious flaxseed oil for health benefits.",
    category: "Oils",
  },
  {
    id: 115,
    title: "Camelina Oil",
    img: Vegetables,
    options: [
      { quantity: "250ml", price: "₹400" },
      { quantity: "500ml", price: "₹750" },
    ],
    unit: "ml",
    para: "Healthy camelina oil for cooking.",
    category: "Oils",
  },
  {
    id: 116,
    title: "Rice Bran Oil",
    img: Vegetables,
    options: [
      { quantity: "1L", price: "₹200" },
      { quantity: "5L", price: "₹900" },
    ],
    unit: "L",
    para: "Nutritious rice bran oil for daily use.",
    category: "Oils",
  },
  {
    id: 117,
    title: "Hazelnut Oil",
    img: Vegetables,
    options: [
      { quantity: "250ml", price: "₹600" },
      { quantity: "500ml", price: "₹1000" },
    ],
    unit: "ml",
    para: "Rich hazelnut oil for gourmet dishes.",
    category: "Oils",
  },
  {
    id: 118,
    title: "Safflower Oil",
    img: Vegetables,
    options: [
      { quantity: "1L", price: "₹220" },
      { quantity: "5L", price: "₹950" },
    ],
    unit: "L",
    para: "Light safflower oil for frying.",
    category: "Oils",
  },
  {
    id: 119,
    title: "Sunflower Oil Blend",
    img: Vegetables,
    options: [
      { quantity: "1L", price: "₹200" },
      { quantity: "5L", price: "₹900" },
    ],
    unit: "L",
    para: "A blend of sunflower oils for versatile cooking.",
    category: "Oils",
  },
  {
    id: 120,
    title: "Peanut Oil",
    img: Vegetables,
    options: [
      { quantity: "1L", price: "₹190" },
      { quantity: "5L", price: "₹850" },
    ],
    unit: "L",
    para: "Flavorful peanut oil for frying.",
    category: "Oils",
  },
  {
    id: 121,
    title: "Gulab Jamun",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹300" },
      { quantity: "1kg", price: "₹550" },
    ],
    unit: "g",
    para: "Soft and sweet gulab jamun soaked in syrup.",
    category: "Sweets",
  },
  {
    id: 122,
    title: "Rasgulla",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹250" },
      { quantity: "1kg", price: "₹450" },
    ],
    unit: "g",
    para: "Delightful rasgullas made from fresh chhena.",
    category: "Sweets",
  },
  {
    id: 123,
    title: "Jalebi",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹150" },
      { quantity: "500g", price: "₹280" },
    ],
    unit: "g",
    para: "Crispy jalebis soaked in sugar syrup.",
    category: "Sweets",
  },
  {
    id: 124,
    title: "Barfi",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "200" },
      { quantity: "500g", price: "₹350" },
    ],
    unit: "g",
    para: "Rich and creamy barfi made with condensed milk.",
    category: "Sweets",
  },
  {
    id: 125,
    title: "Kaju Katli",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹400" },
      { quantity: "500g", price: "₹750" },
    ],
    unit: "g",
    para: "Delicious kaju katli made from cashews.",
    category: "Sweets",
  },
  {
    id: 126,
    title: "Ladoo",
    img: Vegetables,
    options: [
      { quantity: "500g", price: "₹350" },
      { quantity: "1kg", price: "₹650" },
    ],
    unit: "g",
    para: "Sweet ladoos made with gram flour and sugar.",
    category: "Sweets",
  },
  {
    id: 127,
    title: "Peda",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹300" },
      { quantity: "500g", price: "₹550" },
    ],
    unit: "g",
    para: "Soft and sweet pedas made from condensed milk.",
    category: "Sweets",
  },
  {
    id: 128,
    title: "Soan Papdi",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹250" },
      { quantity: "500g", price: "₹450" },
    ],
    unit: "g",
    para: "Flaky soan papdi with a delightful taste.",
    category: "Sweets",
  },
  {
    id: 129,
    title: "Chikki",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹200" },
      { quantity: "500g", price: "₹350" },
    ],
    unit: "g",
    para: "Crunchy chikki made from jaggery and nuts.",
    category: "Sweets",
  },
  {
    id: 130,
    title: "Coconut Burfi",
    img: Vegetables,
    options: [
      { quantity: "250g", price: "₹300" },
      { quantity: "500g", price: "₹550" },
    ],
    unit: "g",
    para: "Sweet coconut burfi made with grated coconut.",
    category: "Sweets",
  },
  //  subcategories: [], // Added subcategories
];
